version: '3.9'

services:
  database:
    restart: unless-stopped
    image: mongo
    container_name: iconpub-mongo
    environment:
      PORT: 27017
    ports:
      - '27017:27017'

  server:
    restart: unless-stopped
    image: yalda/iconpub
    container_name: iconpub
    environment:
      MONGO_HOST: mongo
      PORT: 8080
    volumes:
      - iconpub-mongo:containerPath:ro
    ports:
      - '8080:8080'

volumes:
  iconpub-mongo:
    driver: local
