version: '3.9'

# optional ports are specified throughout for more advanced use cases.

services:
  database:
    restart: unless-stopped
    image: mongo
    container_name: iconpub-mongo
    environment:
      PORT: 27017
    ports:
      - '27017:27017'

  webapp:
    restart: unless-stopped
    image: yalda/iconpub-webapp
    container_name: iconpub-webapp
    environment:
      PORT: 4000
    ports:
      - '4000:4000'

  server:
    restart: unless-stopped
    image: yalda/iconpub-server
    container_name: iconpub-server
    environment:
      NGINX_HOST: 0.0.0.0
      MONGO_HOST: mongo
      PORT: 4001
    ports:
      - '4001:4001'

  gateway:
    restart: unless-stopped
    image: yalda/iconpub-gateway
    container_name: iconpub-gateway
    environment:
      NGINX_HOST: 0.0.0.0
      PORT: 4001
    ports:
      - '443:443'
      - '80:80'
