// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./components/BaseAlert/BaseAlert.vue')['default']
    BaseFeedBack: typeof import('./components/BaseFeedBack/BaseFeedBack.vue')['default']
    BaseModal: typeof import('./components/BaseModal/BaseModal.vue')['default']
    LayoutAbout: typeof import('./components/Layout/LayoutAbout.vue')['default']
    LayoutAuthed: typeof import('./components/Layout/LayoutAuthed.vue')['default']
    LayoutBlank: typeof import('./components/Layout/LayoutBlank.vue')['default']
    LayoutFooter: typeof import('./components/Layout/LayoutFooter.vue')['default']
    LayoutNavAside: typeof import('./components/Layout/LayoutNavAside.vue')['default']
    LayoutNavHeader: typeof import('./components/Layout/LayoutNavHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
