// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseSide: typeof import('./components/BaseSide/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    LayoutFooter: typeof import('./components/LayoutFooter/index.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader/index.vue')['default']
    LayoutSide: typeof import('./components/LayoutSide/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
