// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAbout: typeof import('./components/LayoutFooter/BaseAbout.vue')['default']
    BaseFooter: typeof import('./components/LayoutFooter/BaseFooter.vue')['default']
    BaseModal: typeof import('./components/BaseModal/index.vue')['default']
    LayoutBlank: typeof import('./components/LayoutBlank/index.vue')['default']
    LayoutFooter: typeof import('./components/LayoutFooter/index.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
